# Generated by Django 4.2.3 on 2023-07-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KpiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('general', models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=10, null=True)),
                ('league', models.CharField(blank=True, max_length=255, null=True)),
                ('koef', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_comment', models.URLField(max_length=255, null=True)),
                ('upwork', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'general', 'league', 'koef', 'book_comment', 'upwork'],
            },
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(null=True)),
                ('score', models.CharField(choices=[('0.5', '0.5'), ('-1', '-1')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='main.kpimodel')),
            ],
        ),
        migrations.CreateModel(
            name='SportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('score', models.IntegerField(choices=[(0, 0), (-1, -1)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_items', to='main.kpimodel')),
            ],
        ),
        migrations.CreateModel(
            name='EvrikaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('score', models.IntegerField(choices=[(5, 5), (0, 0)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evrika_items', to='main.kpimodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (0, 0)], null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_title', to='main.bookitem')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='main.kpimodel')),
            ],
        ),
    ]
